name: Release to Maven Central

on:
  release:
    types: [ released ]

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      new-version: ${{  steps.version.outputs.version }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 19
        uses: actions/setup-java@v4
        with:
          java-version: '19'
          distribution: 'corretto'
          cache: maven
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          server-id: central
          server-username: MAVEN_USERNAME
          server-password: MAVEN_CENTRAL_TOKEN

      - name: Get next version
        uses: reecetech/version-increment@2023.9.3
        id: version
        with:
          release_branch: master
          scheme: semver
          increment: patch

      - name: Update version in pom.xml
        run: mvn -B versions:set -DnewVersion=${{ steps.version.outputs.current-version }}  -DgenerateBackupPoms=false

      - name: Verify and deploy
        run: mvn -B deploy --file pom.xml
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_CENTRAL_TOKEN: ${{ secrets.MAVEN_CENTRAL_TOKEN }}
  after-release:
    runs-on: ubuntu-latest
    needs: release

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ vars.DEV_BRANCH }}

      - name: Setup git config
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Setup next version
        run: mvn -B versions:set -DnewVersion=${{ needs.release.outputs.new-version }} -DgenerateBackupPoms=false

      - name: Commit and push
        run: |
          git add -A
          git commit -m "Prepare pom for new iteration"
          git push

      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
